version: '3.8'

networks:
  lms_prod:
    driver: overlay
    attachable: true

volumes:
  postgres_prod:
  redis_prod:
  rabbitmq_prod:
  mongodb_prod:

services:
  # ==================== INFRASTRUCTURE ====================

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - postgres_prod:/var/lib/postgresql/data
    networks:
      - lms_prod
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo:7-jammy
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - mongodb_prod:/data/db
    networks:
      - lms_prod
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    volumes:
      - redis_prod:/data
    networks:
      - lms_prod
    command: redis-server --maxmemory 1gb --maxmemory-policy allkeys-lru
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management-alpine
    volumes:
      - rabbitmq_prod:/var/lib/rabbitmq
    networks:
      - lms_prod
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "15672:15672"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ==================== LOAD BALANCER ====================

  traefik:
    image: traefik:v3.1
    command:
      - "--api.dashboard=true"
      - "--providers.swarm=true"
      - "--providers.swarm.endpoint=unix:///var/run/docker.sock"
      - "--providers.swarm.exposedbydefault=false"
      - "--providers.swarm.network=lms_prod"
      - "--entrypoints.web.address=:80"
      - "--log.level=INFO"
      - "--ping=true"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - lms_prod
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD", "traefik", "healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 3

  # ==================== MICROSERVICES (Production with Replicas) ====================

  genre-service:
    image: ${DOCKER_REGISTRY:-localhost:5000}/genre-service:${VERSION:-latest}
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: password
      REDIS_HOST: redis
      RABBITMQ_HOST: rabbitmq
      SERVER_PORT: 8080
    networks:
      - lms_prod
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        monitor: 30s
        order: start-first
      rollback_config:
        parallelism: 1
        delay: 5s
        order: stop-first
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.genre.rule=PathPrefix(`/api/genres`)"
        - "traefik.http.routers.genre.entrypoints=web"
        - "traefik.http.services.genre.loadbalancer.server.port=8080"
        - "traefik.http.services.genre.loadbalancer.healthcheck.path=/actuator/health"
        - "traefik.http.services.genre.loadbalancer.healthcheck.interval=10s"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  author-service:
    image: ${DOCKER_REGISTRY:-localhost:5000}/author-service:${VERSION:-latest}
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: password
      MONGODB_HOST: mongodb
      MONGODB_PORT: 27017
      MONGODB_DATABASE: author_read_db
      MONGODB_USERNAME: admin
      MONGODB_PASSWORD: admin123
      REDIS_HOST: redis
      RABBITMQ_HOST: rabbitmq
      SERVER_PORT: 8082
    networks:
      - lms_prod
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        monitor: 30s
        order: start-first
      rollback_config:
        parallelism: 1
        delay: 5s
        order: stop-first
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.author.rule=PathPrefix(`/api/authors`)"
        - "traefik.http.routers.author.entrypoints=web"
        - "traefik.http.services.author.loadbalancer.server.port=8082"
        - "traefik.http.services.author.loadbalancer.healthcheck.path=/actuator/health"
        - "traefik.http.services.author.loadbalancer.healthcheck.interval=10s"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8082/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  book-command-service:
    image: ${DOCKER_REGISTRY:-localhost:5000}/book-command-service:${VERSION:-latest}
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: password
      RABBITMQ_HOST: rabbitmq
      SERVER_PORT: 8083
    networks:
      - lms_prod
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        monitor: 30s
        order: start-first
      rollback_config:
        parallelism: 1
        delay: 5s
        order: stop-first
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.book-command.rule=PathPrefix(`/api/books`) && (Method(`POST`) || Method(`PUT`) || Method(`DELETE`))"
        - "traefik.http.routers.book-command.entrypoints=web"
        - "traefik.http.routers.book-command.priority=100"
        - "traefik.http.services.book-command.loadbalancer.server.port=8083"
        - "traefik.http.services.book-command.loadbalancer.healthcheck.path=/actuator/health"
        - "traefik.http.services.book-command.loadbalancer.healthcheck.interval=10s"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8083/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  book-query-service:
    image: ${DOCKER_REGISTRY:-localhost:5000}/book-query-service:${VERSION:-latest}
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: password
      REDIS_HOST: redis
      RABBITMQ_HOST: rabbitmq
      SERVER_PORT: 8085
    networks:
      - lms_prod
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        monitor: 30s
        order: start-first
      rollback_config:
        parallelism: 1
        delay: 5s
        order: stop-first
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.book-query.rule=PathPrefix(`/api/books`) && Method(`GET`)"
        - "traefik.http.routers.book-query.entrypoints=web"
        - "traefik.http.routers.book-query.priority=90"
        - "traefik.http.services.book-query.loadbalancer.server.port=8085"
        - "traefik.http.services.book-query.loadbalancer.healthcheck.path=/actuator/health"
        - "traefik.http.services.book-query.loadbalancer.healthcheck.interval=10s"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8085/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  lending-service:
    image: ${DOCKER_REGISTRY:-localhost:5000}/lending-service:${VERSION:-latest}
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: password
      REDIS_HOST: redis
      RABBITMQ_HOST: rabbitmq
      SERVER_PORT: 8086
    networks:
      - lms_prod
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        monitor: 30s
        order: start-first
      rollback_config:
        parallelism: 1
        delay: 5s
        order: stop-first
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.lending.rule=PathPrefix(`/api/v1/lendings`)"
        - "traefik.http.routers.lending.entrypoints=web"
        - "traefik.http.services.lending.loadbalancer.server.port=8086"
        - "traefik.http.services.lending.loadbalancer.healthcheck.path=/actuator/health"
        - "traefik.http.services.lending.loadbalancer.healthcheck.interval=10s"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8086/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  reader-service:
    image: ${DOCKER_REGISTRY:-localhost:5000}/reader-service:${VERSION:-latest}
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: password
      REDIS_HOST: redis
      RABBITMQ_HOST: rabbitmq
      SERVER_PORT: 8087
    networks:
      - lms_prod
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        monitor: 30s
        order: start-first
      rollback_config:
        parallelism: 1
        delay: 5s
        order: stop-first
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.reader.rule=PathPrefix(`/api/readers`) || PathPrefix(`/api/public`)"
        - "traefik.http.routers.reader.entrypoints=web"
        - "traefik.http.services.reader.loadbalancer.server.port=8087"
        - "traefik.http.services.reader.loadbalancer.healthcheck.path=/actuator/health"
        - "traefik.http.services.reader.loadbalancer.healthcheck.interval=10s"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8087/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  saga-orchestrator:
    image: ${DOCKER_REGISTRY:-localhost:5000}/saga-orchestrator:${VERSION:-latest}
    environment:
      SPRING_PROFILES_ACTIVE: prod
      REDIS_HOST: redis
      GENRE_SERVICE_HOST: genre-service
      GENRE_SERVICE_PORT: 8080
      AUTHOR_SERVICE_HOST: author-service
      AUTHOR_SERVICE_PORT: 8082
      BOOK_SERVICE_HOST: book-command-service
      BOOK_SERVICE_PORT: 8083
      SERVER_PORT: 8084
    networks:
      - lms_prod
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        monitor: 30s
        order: start-first
      rollback_config:
        parallelism: 1
        delay: 5s
        order: stop-first
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.saga.rule=PathPrefix(`/api/catalog`) || PathPrefix(`/api/sagas`)"
        - "traefik.http.routers.saga.entrypoints=web"
        - "traefik.http.services.saga.loadbalancer.server.port=8084"
        - "traefik.http.services.saga.loadbalancer.healthcheck.path=/actuator/health"
        - "traefik.http.services.saga.loadbalancer.healthcheck.interval=10s"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8084/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
